title: Tilt
description: >-
  Kubernetes for Prod, Tilt for Dev
baseurl: ""
url: "https://tilt.dev"
docsurl: "https://docs.tilt.dev"
landingurl: "https://tilt.dev"
blogurl: "https://blog.tilt.dev"
twitter_username: tilt_dev
github_username:  tilt-dev
google_analytics: UA-129150759-1
include:
  - _redirects

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-inline-svg
