title: Tilt
email: hi@windmill.engineering
description: >-
  Local Kubernetes development with no stress
baseurl: ""
url: "https://tilt.dev/"
docsurl: "https://docs.tilt.dev/"
landingurl: "https://tilt.dev/"
blogurl: "https://blog.tilt.dev/"
twitter_username: windmill_eng
github_username:  windmilleng
google_analytics: UA-129150759-1
include:
  - _redirects

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-inline-svg
